In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

# !pip install -qqq pydotplus

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import seaborn as sns
import matplotlib.pyplot as plt

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/noshowappointments/KaggleV2-May-2016.csv

In [2]:
df=pd.read_csv('/kaggle/input/noshowappointments/KaggleV2-May-2016.csv')

In [3]:
df

,PatientId,AppointmentID,Gender,ScheduledDay,AppointmentDay,Age,Neighbourhood,Scholarship,Hipertension,Diabetes,Alcoholism,Handcap,SMS_received,No-show
0,2.987250e+13,5642903,F,2016-04-29T18:38:08Z,2016-04-29T00:00:00Z,62,JARDIM DA PENHA,0,1,0,0,0,0,No
1,5.589978e+14,5642503,M,2016-04-29T16:08:27Z,2016-04-29T00:00:00Z,56,JARDIM DA PENHA,0,0,0,0,0,0,No
2,4.262962e+12,5642549,F,2016-04-29T16:19:04Z,2016-04-29T00:00:00Z,62,MATA DA PRAIA,0,0,0,0,0,0,No
3,8.679512e+11,5642828,F,2016-04-29T17:29:31Z,2016-04-29T00:00:00Z,8,PONTAL DE CAMBURI,0,0,0,0,0,0,No
4,8.841186e+12,5642494,F,2016-04-29T16:07:23Z,2016-04-29T00:00:00Z,56,JARDIM DA PENHA,0,1,1,0,0,0,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
110522,2.572134e+12,5651768,F,2016-05-03T09:15:35Z,2016-06-07T00:00:00Z,56,MARIA ORTIZ,0,0,0,0,0,1,No
110523,3.596266e+12,5650093,F,2016-05-03T07:27:33Z,2016-06-07T00:00:00Z,51,MARIA ORTIZ,0,0,0,0,0,1,No
110524,1.557663e+13,5630692,F,2016-04-27T16:03:52Z,2016-06-07T00:00:00Z,21,MARIA ORTIZ,0,0,0,0,0,1,No
110525,9.213493e+13,5630323,F,2016-04-27T15:09:23Z,2016-06-07T00:00:00Z,38,MARIA ORTIZ,0,0,0,0,0,1,No
110526,3.775115e+14,5629448,F,2016-04-27T13:30:56Z,2016-06-07T00:00:00Z,54,MARIA ORTIZ,0,0,0,0,0,1,No

In [4]:
df.drop(index=99832, inplace=True)

df.drop(['AppointmentID','PatientId','ScheduledDay','AppointmentDay'],inplace=True,axis=1)
df.drop(['Neighbourhood'],inplace=True,axis=1)

df.rename(columns={'Hipertension':'Hypertension'},inplace=True)

df['No-show'] = df['No-show'].map({'No': 0, 'Yes': 1})

df = pd.get_dummies(df, columns=['Gender'])

In [5]:
df = pd.get_dummies(df, columns=["Scholarship", "Hypertension", "Diabetes", "Alcoholism", "Handcap", "SMS_received"])

In [6]:
df

,Age,No-show,Gender_F,Gender_M,Scholarship_0,Scholarship_1,Hypertension_0,Hypertension_1,Diabetes_0,Diabetes_1,Alcoholism_0,Alcoholism_1,Handcap_0,Handcap_1,Handcap_2,Handcap_3,Handcap_4,SMS_received_0,SMS_received_1
0,62,0,True,False,True,False,False,True,True,False,True,False,True,False,False,False,False,True,False
1,56,0,False,True,True,False,True,False,True,False,True,False,True,False,False,False,False,True,False
2,62,0,True,False,True,False,True,False,True,False,True,False,True,False,False,False,False,True,False
3,8,0,True,False,True,False,True,False,True,False,True,False,True,False,False,False,False,True,False
4,56,0,True,False,True,False,False,True,False,True,True,False,True,False,False,False,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
110522,56,0,True,False,True,False,True,False,True,False,True,False,True,False,False,False,False,False,True
110523,51,0,True,False,True,False,True,False,True,False,True,False,True,False,False,False,False,False,True
110524,21,0,True,False,True,False,True,False,True,False,True,False,True,False,False,False,False,False,True
110525,38,0,True,False,True,False,True,False,True,False,True,False,True,False,False,False,False,False,True
110526,54,0,True,False,True,False,True,False,True,False,True,False,True,False,False,False,False,False,True

In [7]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()

age_column = df['Age'].values.reshape(-1, 1)

normalized_age = scaler.fit_transform(age_column)

df['Age'] = normalized_age

In [8]:
df

,Age,No-show,Gender_F,Gender_M,Scholarship_0,Scholarship_1,Hypertension_0,Hypertension_1,Diabetes_0,Diabetes_1,Alcoholism_0,Alcoholism_1,Handcap_0,Handcap_1,Handcap_2,Handcap_3,Handcap_4,SMS_received_0,SMS_received_1
0,0.539130,0,True,False,True,False,False,True,True,False,True,False,True,False,False,False,False,True,False
1,0.486957,0,False,True,True,False,True,False,True,False,True,False,True,False,False,False,False,True,False
2,0.539130,0,True,False,True,False,True,False,True,False,True,False,True,False,False,False,False,True,False
3,0.069565,0,True,False,True,False,True,False,True,False,True,False,True,False,False,False,False,True,False
4,0.486957,0,True,False,True,False,False,True,False,True,True,False,True,False,False,False,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
110522,0.486957,0,True,False,True,False,True,False,True,False,True,False,True,False,False,False,False,False,True
110523,0.443478,0,True,False,True,False,True,False,True,False,True,False,True,False,False,False,False,False,True
110524,0.182609,0,True,False,True,False,True,False,True,False,True,False,True,False,False,False,False,False,True
110525,0.330435,0,True,False,True,False,True,False,True,False,True,False,True,False,False,False,False,False,True
110526,0.469565,0,True,False,True,False,True,False,True,False,True,False,True,False,False,False,False,False,True

In [9]:
missing_values = df.isna().sum()
missing_values

Age               0
No-show           0
Gender_F          0
Gender_M          0
Scholarship_0     0
Scholarship_1     0
Hypertension_0    0
Hypertension_1    0
Diabetes_0        0
Diabetes_1        0
Alcoholism_0      0
Alcoholism_1      0
Handcap_0         0
Handcap_1         0
Handcap_2         0
Handcap_3         0
Handcap_4         0
SMS_received_0    0
SMS_received_1    0
dtype: int64

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 110526 entries, 0 to 110526
Data columns (total 19 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   Age             110526 non-null  float64
 1   No-show         110526 non-null  int64
 2   Gender_F        110526 non-null  bool
 3   Gender_M        110526 non-null  bool
 4   Scholarship_0   110526 non-null  bool
 5   Scholarship_1   110526 non-null  bool
 6   Hypertension_0  110526 non-null  bool
 7   Hypertension_1  110526 non-null  bool
 8   Diabetes_0      110526 non-null  bool
 9   Diabetes_1      110526 non-null  bool
 10  Alcoholism_0    110526 non-null  bool
 11  Alcoholism_1    110526 non-null  bool
 12  Handcap_0       110526 non-null  bool
 13  Handcap_1       110526 non-null  bool
 14  Handcap_2       110526 non-null  bool
 15  Handcap_3       110526 non-null  bool
 16  Handcap_4       110526 non-null  bool
 17  SMS_received_0  110526 non-null  bool
 18  SMS_received_1  110526 non-null  bool
dtypes: bool(17), float64(1), int64(1)
memory usage: 4.3 MB

In [11]:
X = df.drop('No-show', axis=1)
y = df['No-show']

In [12]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [13]:
X_train

,Age,Gender_F,Gender_M,Scholarship_0,Scholarship_1,Hypertension_0,Hypertension_1,Diabetes_0,Diabetes_1,Alcoholism_0,Alcoholism_1,Handcap_0,Handcap_1,Handcap_2,Handcap_3,Handcap_4,SMS_received_0,SMS_received_1
68296,0.034783,False,True,True,False,True,False,True,False,True,False,True,False,False,False,False,True,False
41643,0.573913,False,True,True,False,True,False,True,False,True,False,True,False,False,False,False,True,False
99537,0.234783,True,False,True,False,True,False,True,False,True,False,True,False,False,False,False,True,False
67904,0.400000,False,True,True,False,True,False,True,False,True,False,True,False,False,False,False,True,False
77799,0.513043,True,False,True,False,True,False,True,False,True,False,True,False,False,False,False,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
67898,0.086957,True,False,True,False,True,False,True,False,True,False,True,False,False,False,False,True,False
95015,0.643478,False,True,True,False,True,False,True,False,True,False,True,False,False,False,False,False,True
102238,0.243478,True,False,False,True,True,False,True,False,True,False,True,False,False,False,False,False,True
102528,0.182609,True,False,True,False,True,False,True,False,True,False,True,False,False,False,False,True,False
23423,0.773913,True,False,True,False,False,True,False,True,True,False,True,False,False,False,False,True,False

In [14]:
from sklearn.naive_bayes import GaussianNB, MultinomialNB, BernoulliNB

model = GaussianNB()

model.fit(X_train, y_train)


y_pred = model.predict(X_test)

In [15]:
from sklearn.metrics import classification_report, accuracy_score, confusion_matrix

print(y_pred)

from collections import Counter

unique_values = set(y_pred)

value_counts = Counter(y_pred)

print("Unique values:", unique_values)
print("Count of unique values:")
for value, count in value_counts.items():
    print(f"{value}: {count}")

conf_matrix = confusion_matrix(y_test, y_pred)
tn, fp, fn, tp = conf_matrix.ravel()
(tn, fp, fn, tp)

[1 1 1 ... 1 1 1]
Unique values: {0, 1}
Count of unique values:
1: 21656
0: 450

(361, 17251, 89, 4405)

In [16]:
report = classification_report(y_test, y_pred, output_dict=True)
# Format and print the classification report
print("Classification Report:")
print("{:<15} {:<15} {:<15} {:<15} {:<15}".format("Class", "Precision", "Recall", "F1-Score", "Support"))
for class_label, metrics in report.items():
    if class_label in ['accuracy', 'macro avg', 'weighted avg']:
        continue
    print("{:<15} {:<15.2f} {:<15.2f} {:<15.2f} {:<15}".format(class_label, 
                                                                metrics['precision'], 
                                                                metrics['recall'], 
                                                                metrics['f1-score'], 
                                                                metrics['support']))

Classification Report:
Class           Precision       Recall          F1-Score        Support
0               0.80            0.02            0.04            17612
1               0.20            0.98            0.34            4494

In [17]:
from sklearn.model_selection import GridSearchCV

# Define hyperparameters grid
param_grid = {
    'n_estimators': [50, 100, 150],
    'max_depth': [None, 10, 20],
    'min_samples_split': [2, 5, 10],
    'min_samples_leaf': [1, 2, 4]
}


rf_classifier = RandomForestClassifier(random_state=42)

# Initialize GridSearchCV
grid_search = GridSearchCV(estimator=rf_classifier, param_grid=param_grid, cv=5, scoring='accuracy')

# Fit the grid search to the data
grid_search.fit(X_train, y_train)

# Print the best parameters found
print("Best Parameters:", grid_search.best_params_)

# Get the best model
best_rf_classifier = grid_search.best_estimator_

# Make predictions on test data using the best model
y_pred = best_rf_classifier.predict(X_test)

# Evaluate the best model

from sklearn.metrics import classification_report, accuracy_score, confusion_matrix

print(y_pred)

from collections import Counter

unique_values = set(y_pred)

value_counts = Counter(y_pred)

print("Unique values:", unique_values)
print("Count of unique values:")
for value, count in value_counts.items():
    print(f"{value}: {count}")

conf_matrix = confusion_matrix(y_test, y_pred)
tn, fp, fn, tp = conf_matrix.ravel()
(tn, fp, fn, tp)

report = classification_report(y_test, y_pred, output_dict=True)
# Format and print the classification report
print("Classification Report:")
print("{:<15} {:<15} {:<15} {:<15} {:<15}".format("Class", "Precision", "Recall", "F1-Score", "Support"))
for class_label, metrics in report.items():
    if class_label in ['accuracy', 'macro avg', 'weighted avg']:
        continue
    print("{:<15} {:<15.2f} {:<15.2f} {:<15.2f} {:<15}".format(class_label, 
                                                                metrics['precision'], 
                                                                metrics['recall'], 
                                                                metrics['f1-score'], 
                                                                metrics['support']))

NameError: name 'RandomForestClassifier' is not defined